### PR TITLE
a welcome bot test

### PR DESCRIPTION
**Pull request by leecalcote**
This is the first contribution that I've made to this repo.

I wonder what happens when the welcome bot is enabled on a repo and contributors that have already contributed in the past land a new PR. Will the bot consider them new contributors?

### CODE REVIEW

**Comment by leecalcote** [comment]
I'll let you do the "merge" honors, @ashiscs 😄

**Comment by leecalcote** [comment]
😆

**Comment by ashiscs** [comment]
Sir, we should implement this in other repo as well if all other contributors agree with this..

**Comment by leecalcote** [comment]
@Aisuko what thoughts do you have here? Do you think there's a chance that contributors might consider this an insecure form of encouragement?

**Comment by kushthedude** [comment]
> @Aisuko what thoughts do you have here? Do you think there's a chance that contributors might consider this an insecure form of encouragement?

Why not we write our own welcome bot? It won't take much to have bot with similar functionality.

**Comment by Aisuko** [comment]
@leecalcote Sorry for replay to late, we do not afraid for the insecure question. If we can make a config for the bot reference some first contributor's guidance it would be good.

**Pull request merged**
